name: Build and Deploy Microservice

on:
  repository_dispatch:
    types: [microservice-updated]

jobs:
  build-deploy:
    name: Build and Push Docker Image
    runs-on: self-hosted
    env:
      REGISTRY: ghcr.io/krishnachaitanya018
      IMAGE_TAG: ${{ github.event.client_payload.commit }}
      SERVICE_NAME: ${{ github.event.client_payload.service }}
      REPO_URL: ${{ github.event.client_payload.repo }}

    steps:
      - name: Checkout orchestration repo
        uses: actions/checkout@v4

      - name: Log incoming payload
        run: |
          echo "Triggered by: $REPO_URL"
          echo "Service: $SERVICE_NAME"
          echo "Commit: $IMAGE_TAG"

      - name: Clone microservice repo
        run: |
          echo "Cloning $REPO_URL..."
          git clone https://github.com/$REPO_URL service-code
          cd service-code
          git checkout $IMAGE_TAG
          echo "Checked out commit: $IMAGE_TAG"

      - name: Build Docker image
        run: |
          cd service-code
          echo "Building Docker image..."
          docker build -t $REGISTRY/$SERVICE_NAME:$IMAGE_TAG .
          docker images | grep $SERVICE_NAME

      - name: Push Docker image to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u krishnachaitanya018 --password-stdin
          echo "Pushing image $REGISTRY/$SERVICE_NAME:$IMAGE_TAG..."
          docker push $REGISTRY/$SERVICE_NAME:$IMAGE_TAG


  helm-deploy:
    name: Helm Deploy to Minikube
    runs-on: self-hosted
    needs: build-deploy
    steps:
      - name: Check Minikube status
        run: |
          echo "🔍 Checking if Minikube is running..."
          if ! minikube status | grep -q "Running"; then
            echo "⚠️  Minikube not running. Starting Minikube..."
            minikube start
          else
            echo "✅ Minikube is already running."
          fi
          echo "Current context:"
          kubectl config current-context
          kubectl get nodes

      - name: Helm Deploy to Minikube
        run: |
          echo "🚀 Deploying $SERVICE_NAME to local Minikube cluster..."
          helm upgrade --install $SERVICE_NAME ./helm/$SERVICE_NAME \
            --set image.repository=$REGISTRY/$SERVICE_NAME \
            --set image.tag=$IMAGE_TAG \
            --wait --timeout 180s
        env:
          REGISTRY: ghcr.io/krishnachaitanya018
          IMAGE_TAG: ${{ github.event.client_payload.commit }}
          SERVICE_NAME: user-service

      - name: 🔎 Verify Deployment
        run: |
          echo "Checking pods and services..."
          kubectl get pods
          kubectl get svc
          echo "Deployment complete for $SERVICE_NAME ✅"
