name: Build and Store Microservice Image

on:
  repository_dispatch:
    types: [microservice-updated]

jobs:
  build-and-store:
    name: Build and Store Docker Image Artifact
    runs-on: self-hosted
    env:
      REGISTRY: ghcr.io/krishnachaitanya018
      IMAGE_TAG: ${{ github.event.client_payload.commit }}
      SERVICE_NAME: ${{ github.event.client_payload.service }}
      REPO_URL: ${{ github.event.client_payload.repo }}

    steps:
      - name: Checkout orchestration repo
        uses: actions/checkout@v4

      - name: Log incoming payload
        run: |
          echo "Triggered by: $REPO_URL"
          echo "Service: $SERVICE_NAME"
          echo "Commit SHA: $IMAGE_TAG"

      - name: Clone microservice repo
        run: |
          echo "Cloning $REPO_URL..."
          git clone https://github.com/$REPO_URL service-code
          cd service-code
          git checkout $IMAGE_TAG
          echo "Checked out commit: $IMAGE_TAG"

      - name: Build Docker image
        run: |
          cd service-code
          echo "Building Docker image..."
          docker build -t $SERVICE_NAME:$IMAGE_TAG .
          docker images | grep $SERVICE_NAME

      - name: Save Docker image as artifact
        run: |
          mkdir -p artifacts
          docker save -o artifacts/${SERVICE_NAME}_${IMAGE_TAG}.tar $SERVICE_NAME:$IMAGE_TAG
          ls -lh artifacts/

      - name: Upload image artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ env.SERVICE_NAME }}
          path: artifacts/${{ env.SERVICE_NAME }}_${{ env.IMAGE_TAG }}.tar
